In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('playerStats.csv')

In [3]:
print data.head()

    Map  Player  Kills  Deaths   ADR  KAST%  Rating  \
0  Nuke    4216     22      19  85.0   69.0    1.17   
1  Nuke    3543     26      23  83.5   58.6    1.10   
2  Nuke    3972     20      23  78.2   75.9    1.02   
3  Nuke    2476     17      20  68.1   79.3    0.97   
4  Nuke    2299     17      20  66.3   65.5    0.86   

                                             MatchID  
0  2311133/binary-dragons-vs-alpha-binary-dragons...  
1  2311133/binary-dragons-vs-alpha-binary-dragons...  
2  2311133/binary-dragons-vs-alpha-binary-dragons...  
3  2311133/binary-dragons-vs-alpha-binary-dragons...  
4  2311133/binary-dragons-vs-alpha-binary-dragons...  


In [4]:
dataset = data.as_matrix()
data1 = dataset[:20000,4:7]
print data1

[[85.0 69.0 1.17]
 [83.5 58.6 1.1]
 [78.2 75.9 1.02]
 ..., 
 [86.3 58.6 1.14]
 [59.7 75.9 0.95]
 [91.9 88.0 1.52]]


In [5]:
print data1.shape

(20000, 3)


In [6]:
plt.figure(figsize=(10,5))
plt.scatter(x = data1[:,0], y = data1[:,2])
plt.show()

In [6]:
def SSE(m,c,d):
    error = 0
    for i in range(d.shape[0]):
        target = d[i,2]
        output = m*d[i,0]+c
        error += (target - output)**2
    return error

In [24]:
def gradient_descent(m_start,c_start,d,steps):
    n = d.shape[0]
    m = m_start
    c = c_start
    mgrad = 0.0
    cgrad = 0.0
    for i in range(steps):
        for i in range(n):
            x = d[i,0]
            y = d[i,2]
            print x, y
            dm = float(-((2/n) * x * (y - (m*x + c))))
            dc = float(-((2/n)*(y-m*x-c)))
            print dm, dc
            mgrad += dm
            cgrad += dc
        m = m - 0.0001*mgrad
        c = c - 0.0001*cgrad
        sse = SSE(m, c, d)
        print sse
    

In [25]:
m = 0.5
c = 0.1
steps = 1
gradient_descent(m,c,data1,steps)

85.0 1.17
0.0 0.0
83.5 1.1
0.0 0.0
78.2 1.02
0.0 0.0
68.1 0.97
0.0 0.0
66.3 0.86
0.0 0.0
99.8 1.35
0.0 0.0
78.2 1.2
0.0 0.0
85.6 1.03
0.0 0.0
66.6 1.0
0.0 0.0
57.5 0.87
0.0 0.0
118.6 1.82
0.0 0.0
114.8 1.67
0.0 0.0
90.0 1.55
0.0 0.0
59.2 1.22
0.0 0.0
68.9 1.07
0.0 0.0
85.0 1.01
0.0 0.0
65.8 0.81
0.0 0.0
44.7 0.55
0.0 0.0
56.2 0.52
0.0 0.0
54.2 0.5
0.0 0.0
113.7 1.42
0.0 0.0
86.1 1.28
0.0 0.0
77.9 1.15
0.0 0.0
62.5 0.81
0.0 0.0
43.7 0.69
0.0 0.0
100.4 1.23
0.0 0.0
73.1 1.1
0.0 0.0
73.9 1.08
0.0 0.0
59.6 0.99
0.0 0.0
55.0 0.72
0.0 0.0
86.6 1.12
0.0 0.0
92.6 1.0
0.0 0.0
66.6 0.9
0.0 0.0
46.7 0.65
0.0 0.0
53.1 0.62
0.0 0.0
117.0 1.7
0.0 0.0
88.3 1.33
0.0 0.0
86.2 1.32
0.0 0.0
56.7 1.09
0.0 0.0
56.6 0.72
0.0 0.0
77.4 1.33
0.0 0.0
85.7 1.21
0.0 0.0
78.1 0.93
0.0 0.0
69.8 0.92
0.0 0.0
62.3 0.87
0.0 0.0
94.9 1.32
0.0 0.0
88.1 1.18
0.0 0.0
66.9 1.05
0.0 0.0
76.6 1.02
0.0 0.0
48.8 0.65
0.0 0.0
93.7 1.17
0.0 0.0
72.1 1.07
0.0 0.0
77.9 1.06
0.0 0.0
78.5 1.05
0.0 0.0
58.7 0.77
0.0 0.0
108.3 1.59
0.